CREATE TABLE `professionalReports` (
	`id` varchar(64) NOT NULL,
	`inspectionId` varchar(64) NOT NULL,
	`userId` int NOT NULL,
	`reportNumber` varchar(255),
	`reportDate` date,
	`inspectorName` text,
	`inspectorCertification` varchar(255),
	`employerName` text,
	`clientName` text,
	`clientLocation` text,
	`clientContact` text,
	`clientApprovalName` text,
	`clientApprovalTitle` text,
	`executiveSummary` text,
	`nextExternalInspectionClient` date,
	`nextExternalInspectionAPI` date,
	`nextInternalInspection` date,
	`nextUTInspection` date,
	`governingComponent` varchar(255),
	`api510Compliant` boolean DEFAULT true,
	`asmeCompliant` boolean DEFAULT true,
	`riskClassification` enum('low','medium','high','critical') DEFAULT 'medium',
	`operationalEfficiencyScore` int,
	`complianceNotes` text,
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `professionalReports_id` PRIMARY KEY(`id`)
);
